volumes:
  production_postgres_data: {}
  production_redis_data: {}
  
services:
  django: &django
    build:
      context: .
      dockerfile: docker/production/django/Dockerfile

    image: project_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: docker/production/postgres/Dockerfile
    image: project_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres
      -
  redis:
    image: docker.io/redis:6
    volumes:
      - production_redis_data:/data
    

  celeryworker:
    <<: *django
    image: project_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: project_production_celerybeat
    command: /start-celerybeat

